# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 23:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('camera', models.CharField(choices=[('Nikon', 'Nikon'), ('Canon', 'Canon'), ('Sony', 'Sony')], default='Nikon', max_length=5)),
                ('services', multiselectfield.db.fields.MultiSelectField(choices=[('Weddings', 'Weddings'), ('Birthdays', 'Birthdays'), ('School', 'School'), ('Family', 'Family'), ('Portrait', 'Portrait')], default='Portrait', max_length=10)),
                ('bio', models.TextField(max_length=1000)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('photo_style', multiselectfield.db.fields.MultiSelectField(choices=[('Color', 'Color'), ('Black_White', 'Black and White'), ('Future', 'Future'), ('Western', 'Western'), ('Architecture', 'Architecture')], default='Color', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
