# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='photo_style',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Color', 'Color'), ('Black_White', 'Black and White'), ('Future', 'Future'), ('Western', 'Western'), ('Architecture', 'Architecture')], default='Color', max_length=50),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Weddings', 'Weddings'), ('Birthdays', 'Birthdays'), ('School', 'School'), ('Family', 'Family'), ('Portrait', 'Portrait')], default='Portrait', max_length=50),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='website',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
